<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="BranchService.Contracts" Version="1.0.7" />
      <PackageReference Include="MassTransit" Version="8.5.7" />
      <PackageReference Include="MassTransit.AspNetCore" Version="7.3.1" />
      <PackageReference Include="MassTransit.RabbitMQ" Version="8.5.7" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.17" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.17">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.17" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.17">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
      <PackageReference Include="QueueService.Contracts" Version="1.0.7" />
      <PackageReference Include="UserService.Contracts" Version="1.0.7" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\RecommendationService.Domain\RecommendationService.Domain.csproj" />
    </ItemGroup>

</Project>
